import re

class TarnishedTalk:
    templateList: list[str] = [
        "____ ahead",
        "no ____ ahead",
        "____ required ahead",
        "be wary of ____",
        "try ____",
        "likely ____",
        "first off, ____",
        "seek ____",
        "still no ____...",
        "why is it always ____?",
        "if only I had a ____...",
        "didn't expect ____...",
        "visions of ____...",
        "could this be a ____?",
        "time for ____",
        "____, O ____",
        "behold, ____!",
        "offer ____",
        "praise the ____!",
        "let there be ____",
        "ahh, ____...",
        "____",
        "____!",
        "____?",
        "____..."
    ]

    wordsList: dict[list[str]] = {
        "Enemies 1" : [
            "enemy",
            "weak foe",
            "strong foe",
            "monster",
            "dragon",
            "boss",
            "sentry",
            "group",
            "pack",
            "decoy",
            "undead",
            "soldier",
            "knight",
            "cavalier",
            "archer",
            "sniper",
            "mage",
            "ordnance",
            "monarch",
            "lord",
            "demi-human",
            "outsider",
            "giant",
            "horse",
        ],
        "Enemies 2" : [  
            "dog",
            "wolf",
            "rat",
            "beast",
            "bird",
            "raptor",
            "snake",
            "crab",
            "prawn",
            "octopus",
            "bug",
            "scarab",
            "slug",
            "wraith",
            "skeleton",
            "monstrosity",
            "ill-omened creature"
        ],
        "People 1" : [
            "Tarnished",
            "warrior",
            "swordfighter",
            "knight",
            "samurai",
            "sorcerer",
            "cleric",
            "sage",
            "merchant",
            "teacher",
            "master",
            "friend",
            "lover",
            "old dear",
            "old codger",
            "angel",
            "fat coinpurse",
            "pauper",
        ],
        "People 2" : [
            "good sort",
            "wicked sort",
            "plump sort",
            "skinny sort",
            "lovable sort",
            "pathetic sort",
            "strange sort",
            "nimble sort",
            "laggardly sort",
            "invisible sort",
            "unfathomable sort",
            "giant sort",
        ],
        "People 3" : [
            "sinner",
            "thief",
            "liar",
            "dastard",
            "traitor",
            "pair",
            "trio",
            "noble",
            "aristocrat",
            "hero",
            "champion",
            "monarch",
            "lord",
            "god",
        ],
        "Things 1" : [
            "item",
            "necessary item",
            "precious item",
            "something",
            "something incredible",
            "treasure chest",
            "corpse",
            "coffin",
            "trap",
            "armament",
            "shield",
            "bow",
            "projectile weapon",
            "armor",
            "talisman",
            "skill",
            "sorcery",
            "incantation",
            "map",
            "material",
            "flower",
            "grass",
        ],
        "Things 2" : [
            "tree",
            "fruit",
            "seed",
            "mushroom",
            "tear",
            "crystal",
            "butterfly",
            "bug",
            "dung",
            "grace",
            "door",
            "key",
            "ladder",
            "lever",
            "lift",
            "spritspring",
            "sending gate",
            "stone astrolabe",
            "Birdseye Telescope",
            "message",
            "bloodstain",
            "Erdtree",
            "Elden Ring"
        ],
        "Battle Tactics" : [
            "close-quarters battle",
            "ranged battle",
            "horseback battle",
            "luring out",
            "defeating one-by-one",
            "taking on all at once",
            "rushing in",
            "stealth",
            "mimicry",
            "confusion",
            "pursuit",
            "fleeing",
            "summoning",
            "circling around",
            "jumping off",
            "dashing through",
            "brief respite"
        ],
        "Actions" : [
            "attacking",
            "jump attack",
            "running attack",
            "critical hit",
            "two-handing",
            "blocking",
            "parrying",
            "guard counter",
            "sorcery",
            "incantation",
            "skill",
            "summoning",
            "throwing",
            "healing",
            "running",
            "rolling",
            "backstepping",
            "jumping",
            "crouching",
            "target lock",
            "item crafting"
        ],
        "Situations 1" : [
            "morning",
            "noon",
            "evening",
            "night",
            "clear sky",
            "overcast",
            "rain",
            "storm",
            "mist",
            "snow",
            "patrolling",
            "procession",
            "crowd",
            "surprise attack",
            "ambush",
            "pincer attack",
            "beating to a pulp",
            "battle",
            "reinforcements",
            "ritual",
            "explosion",
        ],
        "Situations 2" : [
            "high spot",
            "defensible spot",
            "climbable spot",
            "crossable spot",
            "bright spot",
            "dark spot",
            "open area",
            "cramped area",
            "hiding place",
            "sniping spot",
            "recon spot",
            "safety",
            "danger",
            "gorgeous view",
            "detour",
            "hidden path",
            "shortcut",
            "dead end",
            "looking away",
            "unnoticed",
            "out of stamina"
        ],
        "Places 1" : [
            "high road",
            "checkpoint",
            "bridge",
            "castle",
            "fort",
            "city",
            "ruins",
            "tower",
            "camp site",
            "house",
            "cemetary",
            "underground tomb",
        ],
        "Places 2" : [
            "tunnel",
            "cave",
            "evergaol",
            "great tree",
            "cellar",
            "surface",
            "underground",
            "forest",
            "river",
            "lake",
            "bog",
            "mountain",
            "valley",
            "cliff",
            "nest",
            "hole"
        ],
        "Directions" : [
            "east",
            "west",
            "south",
            "north",
            "ahead",
            "behind",
            "left",
            "right",
            "center",
            "up",
            "down",
            "edge"
        ],
        "Body Parts" : [
            "head",
            "stomach",
            "back",
            "arms",
            "legs",
            "rump",
            "tail",
            "core",
            "fingers"
        ],
        "Affinities" : [
            "physical",
            "standard",
            "striking",
            "slashing",
            "piercing",
            "fire",
            "lightning",
            "magic",
            "holy",
            "poison",
            "toxic",
            "scarlet rot",
            "blood loss",
            "frost",
            "sleep",
            "madness",
            "death"
        ],
        "Concepts 1" : [
            "life",
            "Death",
            "light",
            "dark",
            "stars",
            "fire",
            "Order",
            "chaos",
            "joy",
            "wrath",
            "suffering",
            "sadness",
            "comfort",
            "bliss",
            "misfortune",
            "good fortune",
            "bad luck",
            "hope",
            "despair",
            "victory",
            "defeat",
        ],
        "Concepts 2" : [
            "research",
            "faith",
            "rot",
            "loyalty",
            "injustice",
            "secret",
            "opportunity",
            "pickle",
            "clue",
            "friendship",
            "love",
            "bravery",
            "vigor",
            "fortitude",
            "confidence",
            "distracted",
            "unguarded",
        ],
        "Concepts 3" : [
            "introspection",
            "regret",
            "resignation",
            "futility",
            "on the brink",
            "betrayal",
            "revenge",
            "destruction",
            "recklessness",
            "calmness",
            "vigilance",
            "tranquility",
            "sound",
            "tears",
            "sleep",
            "depths",
            "dregs",
            "fear",
            "sacrifice",
            "ruin"
        ],
        "Phrases 1" : [
            "good luck",
            "look carefully",
            "listen carefully",
            "think carfeully",
            "well done",
            "I did it!",
            "I've failed...",
            "here!",
            "not here!",
            "don't you dare!",
            "do it!",
            "I can't take this...",
            "don't think",
            "so lonely...",
            "here again...",
            "just getting started",
            "stay calm",
            "keep moving",
            "turn back",
            "give up",
            "don't give up",
        ],
        "Phrases 2" : [
            "help me...",
            "I don't believe it...",
            "too high up",
            "I want to go home...",
            "it's like a dream...",
            "seems familiar",
            "beautiful...",
            "you don't have the right",
            "are you ready?"
        ],
    }

    categoryList = [
        "Enemies 1",
        "Enemies 2",
        "People 1",
        "People 2",
        "People 3",
        "Things 1",
        "Things 2",
        "Battle Tactics",
        "Actions",
        "Situations 1",
        "Situations 2",
        "Places 1",
        "Places 2",
        "Directions",
        "Body Parts",
        "Affinities",
        "Concepts 1",
        "Concepts 2",
        "Concepts 3",
        "Phrases 1",
        "Phrases 2"
    ]

    conjunctionList: list[str] = [
        "None",
        "and then",
        "or",
        "but",
        "therefore",
        "in short",
        "except",
        "by the way",
        "so to speak",
        "all the more",
        ","
    ]
    
    def __init__(self):
        super().__init__()
        self.templateFirst = self.templateList[0]
        self.categoryFirst = self.categoryList[0]
        self.wordFirst = self.wordsList[self.categoryFirst][0]
        self.conjunction = self.conjunctionList[0]
        self.templateSecond = self.templateList[0]
        self.categorySecond = self.categoryList[0]
        self.wordSecond = self.wordsList[self.categorySecond][0]
    
    def getWordSublist(self, category: str) -> list[str]: return self.wordsList[category]
    
    def getChunk(self, second=False) -> str:
        if not second:
            return re.sub("____", self.wordFirst,self.templateFirst)
        else:
            return re.sub("____", self.wordSecond,self.templateSecond)
    
    def getMessage(self) -> str:
        firstHalf = self.getChunk()
        secondHalf = self.getChunk(True)
        if self.conjunction == self.conjunctionList[0]:
            return firstHalf
        elif self.conjunction == ",":
                return firstHalf + self.conjunction + " " + secondHalf
        else:
            return firstHalf + " " + self.conjunction + " " + secondHalf